export const EXPANDABLE_TEXT = "changeState";
export const MUTATION_TEXT = "handleMutation";
export const FILTER_BY = "Filtros";
export const REMOVE_FILTERS = "Quitar filtros";
export const PLACEHOLDER_FROM = "$ Desde:";
export const PLACEHOLDER_TO = "$ Hasta:";
export const ASCENDING = "Ascendente";
export const DESCENDING = "Descendente";
export const NO_AVAILABLE_FILTERS = "No hay filtros disponibles";